### ISSUE TITLE
cgo static issue

### ISSUE THREAD

**Issue by BuckarooBanzay** [minetest-go/mtui#181]
```
ui_1            | goroutine 1 [running]:
ui_1            | runtime.systemstack_switch()
ui_1            | 	/opt/hostedtoolcache/go/1.20.7/x64/src/runtime/asm_amd64.s:463 fp=0xc000056780 sp=0xc000056778 pc=0x467840
ui_1            | runtime.main()
ui_1            | 	/opt/hostedtoolcache/go/1.20.7/x64/src/runtime/proc.go:170 +0x6d fp=0xc0000567e0 sp=0xc000056780 pc=0x43972d
ui_1            | runtime.goexit()
ui_1            | 	/opt/hostedtoolcache/go/1.20.7/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000567e8 sp=0xc0000567e0 pc=0x469a61
ui_1            | 
ui_1            | rax    0x0
ui_1            | rbx    0x20a43c0
ui_1            | rcx    0xdbdcac
ui_1            | rdx    0x6
ui_1            | rdi    0x1
ui_1            | rsi    0x1
ui_1            | rbp    0x1
ui_1            | rsp    0x7ffe381a03f0
ui_1            | r8     0x7ffe381a04c0
ui_1            | r9     0x0
ui_1            | r10    0x8
ui_1            | r11    0x246
ui_1            | r12    0x6
ui_1            | r13    0x16
ui_1            | r14    0x1ada680
ui_1            | r15    0x1
ui_1            | rip    0xdbdcac
ui_1            | rflags 0x246
ui_1            | cs     0x33
ui_1            | fs     0x0
ui_1            | gs     0x0
ui_1            | runtime/cgo: pthread_create failed: Operation not permitted
ui_1            | SIGABRT: abort
ui_1            | PC=0xdbdcac m=0 sigcode=18446744073709551610
ui_1            | 
ui_1            | goroutine 0 [idle]:
ui_1            | runtime: g 0: unknown pc 0xdbdcac
ui_1            | stack: frame={sp:0x7fff200cfde0, fp:0x0} stack=[0x7fff1f8d1360,0x7fff200d0370)
ui_1            | 0x00007fff200cfce0:  0x0000000000405c40 <runtime.mmap.func1+0x0000000000000000>  0x00007fff200cfcd8 
ui_1            | 0x00007fff200cfcf0:  0x00007ff44695d000  0x0000000000407000 <runtime.cgoIsGoPointer+0x0000000000000020> 
ui_1            | 0x00007fff200cfd00:  0x0000003200000003  0x00000000ffffffff 
ui_1            | 0x00007fff200cfd10:  0x00007fff200cfd58  0x0000000000419bf9 <runtime.sysMapOS+0x0000000000000039> 
ui_1            | 0x00007fff200cfd20:  0x00007ff444848000  0x0000000000405c40 <runtime.mmap.func1+0x0000000000000000> 
ui_1            | 0x00007fff200cfd30:  0x0000000000419b85 <runtime.sysHugePageOS+0x0000000000000065>  0x00007ff446a00000 
ui_1            | 0x00007fff200cfd40:  0x0000000000200000  0x000000000000000e 
ui_1            | 0x00007fff200cfd50:  0x00007ff400000000  0x00007fff200cfd88 
ui_1            | 0x00007fff200cfd60:  0x0000000000419a87 <runtime.sysUsedOS+0x0000000000000027>  0x0000000000da6290 
ui_1            | 0x00007fff200cfd70:  0x0000000000407000 <runtime.cgoIsGoPointer+0x0000000000000020>  0x0000000000000000 
ui_1            | 0x00007fff200cfd80:  0x0000000000000120  0x00000012200cfdf8 
ui_1            | 0x00007fff200cfd90:  0x0000000000e4f620  0x000000001c000004 
ui_1            | 0x00007fff200cfda0:  0x0000000000000110  0x0000000000000000 
ui_1            | 0x00007fff200cfdb0:  0x0000000000002000  0x0000000000002030 
ui_1            | 0x00007fff200cfdc0:  0x0000000000000004  0x0000003400000012 
ui_1            | 0x00007fff200cfdd0:  0x0000000000000000  0x0000000000dbdc9e 
ui_1            | 0x00007fff200cfde0: <0x0000000000000000  0x000000770000007c 
ui_1            | 0x00007fff200cfdf0:  0x0000005b0000006e  0x000080c000000000 
ui_1            | 0x00007fff200cfe00:  0x00007fff200d0020  0x0000000000dffe21 
ui_1            | 0x00007fff200cfe10:  0x00007ff444727640  0x00007fff200d00f0 
ui_1            | 0x00007fff200cfe20:  0x00007fff200cff5e  0x00007fff200cff5f 
ui_1            | 0x00007fff200cfe30:  0x0000000000000000  0x0000000000dbc129 
ui_1            | 0x00007fff200cfe40:  0x0000000000800280 <modernc.org/sqlite/lib.Xsqlite3GetInt32+0x00000000000001e0>  0x0000000000000000 
ui_1            | 0x00007fff200cfe50:  0x00000000003d0f00  0x00007ff444727910 
ui_1            | 0x00007fff200cfe60:  0x00007ff444727910  0x0088012b9aed4c00 
ui_1            | 0x00007fff200cfe70:  0x00000000032b33c0  0x0000000000000006 
ui_1            | 0x00007fff200cfe80:  0x000000000146b02a  0x00007fff200d01b0 
ui_1            | 0x00007fff200cfe90:  0x0000000001ada680  0x0000000000daf1c6 
ui_1            | 0x00007fff200cfea0:  0x0000000001b0ab20  0x00000000004013df 
ui_1            | 0x00007fff200cfeb0:  0x0000000000000020  0x00007ff444727640 
ui_1            | 0x00007fff200cfec0:  0x0000000000000000  0x00007fff200d00f0 
ui_1            | 0x00007fff200cfed0:  0x00007ff444727640  0x0000000000dbcf5a 
ui_1            | runtime: g 0: unknown pc 0xdbdcac
ui_1            | stack: frame={sp:0x7fff200cfde0, fp:0x0} stack=[0x7fff1f8d1360,0x7fff200d0370)
ui_1            | 0x00007fff200cfce0:  0x0000000000405c40 <runtime.mmap.func1+0x0000000000000000>  0x00007fff200cfcd8 
ui_1            | 0x00007fff200cfcf0:  0x00007ff44695d000  0x0000000000407000 <runtime.cgoIsGoPointer+0x0000000000000020> 
ui_1            | 0x00007fff200cfd00:  0x0000003200000003  0x00000000ffffffff 
ui_1            | 0x00007fff200cfd10:  0x00007fff200cfd58  0x0000000000419bf9 <runtime.sysMapOS+0x0000000000000039> 
ui_1            | 0x00007fff200cfd20:  0x00007ff444848000  0x0000000000405c40 <runtime.mmap.func1+0x0000000000000000> 
ui_1            | 0x00007fff200cfd30:  0x0000000000419b85 <runtime.sysHugePageOS+0x0000000000000065>  0x00007ff446a00000 
ui_1            | 0x00007fff200cfd40:  0x0000000000200000  0x000000000000000e 
ui_1            | 0x00007fff200cfd50:  0x00007ff400000000  0x00007fff200cfd88 
ui_1            | 0x00007fff200cfd60:  0x0000000000419a87 <runtime.sysUsedOS+0x0000000000000027>  0x0000000000da6290 
ui_1            | 0x00007fff200cfd70:  0x0000000000407000 <runtime.cgoIsGoPointer+0x0000000000000020>  0x0000000000000000 
ui_1            | 0x00007fff200cfd80:  0x0000000000000120  0x00000012200cfdf8 
ui_1            | 0x00007fff200cfd90:  0x0000000000e4f620  0x000000001c000004 
ui_1            | 0x00007fff200cfda0:  0x0000000000000110  0x0000000000000000 
ui_1            | 0x00007fff200cfdb0:  0x0000000000002000  0x0000000000002030 
ui_1            | 0x00007fff200cfdc0:  0x0000000000000004  0x0000003400000012 
ui_1            | 0x00007fff200cfdd0:  0x0000000000000000  0x0000000000dbdc9e 
ui_1            | 0x00007fff200cfde0: <0x0000000000000000  0x000000770000007c 
ui_1            | 0x00007fff200cfdf0:  0x0000005b0000006e  0x000080c000000000 
ui_1            | 0x00007fff200cfe00:  0x00007fff200d0020  0x0000000000dffe21 
ui_1            | 0x00007fff200cfe10:  0x00007ff444727640  0x00007fff200d00f0 
ui_1            | 0x00007fff200cfe20:  0x00007fff200cff5e  0x00007fff200cff5f 
ui_1            | 0x00007fff200cfe30:  0x0000000000000000  0x0000000000dbc129 
ui_1            | 0x00007fff200cfe40:  0x0000000000800280 <modernc.org/sqlite/lib.Xsqlite3GetInt32+0x00000000000001e0>  0x0000000000000000 
ui_1            | 0x00007fff200cfe50:  0x00000000003d0f00  0x00007ff444727910 
ui_1            | 0x00007fff200cfe60:  0x00007ff444727910  0x0088012b9aed4c00 
ui_1            | 0x00007fff200cfe70:  0x00000000032b33c0  0x0000000000000006 
ui_1            | 0x00007fff200cfe80:  0x000000000146b02a  0x00007fff200d01b0 
ui_1            | 0x00007fff200cfe90:  0x0000000001ada680  0x0000000000daf1c6 
ui_1            | 0x00007fff200cfea0:  0x0000000001b0ab20  0x00000000004013df 
ui_1            | 0x00007fff200cfeb0:  0x0000000000000020  0x00007ff444727640 
ui_1            | 0x00007fff200cfec0:  0x0000000000000000  0x00007fff200d00f0 
ui_1            | 0x00007fff200cfed0:  0x00007ff444727640  0x0000000000dbcf5a 
ui_1            | 
ui_1            | goroutine 1 [running]:
ui_1            | runtime.systemstack_switch()
ui_1            | 	/opt/hostedtoolcache/go/1.20.7/x64/src/runtime/asm_amd64.s:463 fp=0xc000056780 sp=0xc000056778 pc=0x467840
ui_1            | runtime.main()
ui_1            | 	/opt/hostedtoolcache/go/1.20.7/x64/src/runtime/proc.go:170 +0x6d fp=0xc0000567e0 sp=0xc000056780 pc=0x43972d
ui_1            | runtime.goexit()
ui_1            | 	/opt/hostedtoolcache/go/1.20.7/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000567e8 sp=0xc0000567e0 pc=0x469a61
ui_1            | 
ui_1            | rax    0x0
ui_1            | rbx    0x32b33c0
ui_1            | rcx    0xdbdcac
ui_1            | rdx    0x6
ui_1            | rdi    0x1
ui_1            | rsi    0x1
ui_1            | rbp    0x1
ui_1            | rsp    0x7fff200cfde0
ui_1            | r8     0x7fff200cfeb0
ui_1            | r9     0x0
ui_1            | r10    0x8
ui_1            | r11    0x246
ui_1            | r12    0x6
ui_1            | r13    0x16
ui_1            | r14    0x1ada680
ui_1            | r15    0x1
ui_1            | rip    0xdbdcac
ui_1            | rflags 0x246
ui_1            | cs     0x33
ui_1            | fs     0x0
ui_1            | gs     0x0

```

**Comment by BuckarooBanzay** [comment]
solved with docker upgrade to `> 20.0`
